name: "deploy-rs"
on:
  push:
    branches: [ master ]
    paths:
    - 'flake.nix'
    - 'hosts/media/**'
    - 'secrets/**'
    - 'common/nixos/**'
    - '.github/workflows/**'
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Check Nix Flake Inputs
      uses: DeterminateSystems/flake-checker-action@main
      with:
        send-statistics: false
    - name: Install Tailscale
      uses: tailscale/github-action@main
      with:
        oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
        oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
        args: --ssh
        tags: tag:github
    - name: Create SSH key
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_ed25519
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
      with:
        extra_conf: |
          experimental-features = nix-command flakes
    - name: Cache Nix Build
      uses: DeterminateSystems/magic-nix-cache-action@main
    - name: Deploy Nix FLake
      run: |
        nix run github:serokell/deploy-rs .#media
        sudo tailscale logout
