name: "deploy-rs"
on:
  push:
    branches: [ master ]
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Install Tailscale
      uses: tailscale/github-action@HEAD
      with:
        authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
        args: --ssh
    - name: Create SSH key
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_ed25519
        # echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
    - name: Install Nix
      uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes
    - name: Cachix Build Cache
      uses: cachix/cachix-action@v12
      with:
        name: mich-murphy
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix flake check
    - run: nix run github:serokell/deploy-rs .#media
    - run: sudo tailscale logout
